### ISSUE TITLE
Offer to help! 

### ISSUE THREAD

**Issue by AbsolofDarkness** [DunkleMango/StarboundModManager#7]
Hello there! I stumbled across your application while looking for Starbound mod managers, and am really liking how it's looking! I noticed your most recent push was the beginning of a github pages site. I have web development experience and if you don't have any other plans, I'd like to build the website for you while you work on the application!

**Comment by DunkleMango** [comment]
Hey, first of all I'm glad you like the Application and that you offer your help!

It's true that I recently pushed a github pages site, which is just a "HelloWorld" at the moment.
I'm currently working on it offline on my computer to test a few things before it goes live.
Also this is kind of a chance for me to get some HTML, CSS and Javascript skills, since we don't really get that much practice here at university.

Nonetheless if you want to help, it would be greatly appreciated and maybe I can learn from your experience in the field as well! :)
I will attach an image of my progress on the site, so you can decide what to do.
If you have questions left feel free to ask!

Do you think the Application is missing some features or have ideas how it can be improved?

![grafik](https://user-images.githubusercontent.com/44678770/62123821-11e67f80-b2c9-11e9-867f-008f4c045bbd.png)

**Comment by AbsolofDarkness** [comment]
Thanks for allowing me to help! While I definitely wouldn't say I'm a professional, It is what I took classes on :P. Is there a specific way you would like me to do this? I also did have a potential suggestion, I just don't know how complicated it'd be. To be more user friendly, maybe for each mod, it can display the name of the mod, instead of just the steam id. I haven't worked with Java, so I don't know if it could be done, or if it'd require an API or something similar.

**Comment by DunkleMango** [comment]
If you have taken classes on this topic, thats also just fine!
Maybe we both can experiment a little on here then. :D

I took a look at your profile and portfolio, to see what you have worked on and it looks really nice!
I did stumble upon your info, which states that you are trying to get hired.
Just to be clear, I have to inform you that since I don't even get revenue from this project myself, I won't be able to pay for your service.
If you still want to help out, that would be awesome though! :)

If you want to, you could organize the documentation and download page for example.
I did not work on them yet.

On the other hand, there is the start page that is still missing a nice Header as well as a clear layout for the user (like where should each component be placed, e.g. the tutorial and download should be somewhere at the top so that it's hard to miss it).

I've also created a JS file that generates HTML from the Github-API and constructs the commit-history dynamically so that the user can see the changes that have been made (maybe we could create a more user-friendly summary per release?).
I'm also struggling with the many different browser-behaviours, making me do something like a custom scrollbar (if they even allow it to be modified) like 4 times so that every browser gets its own specific code. 🙄 

If you want to, you could also rework the general page design.
I'm just a fan of dark website styles as you can see. :)

Also, I'll have a look at what can be done to get the mods names from the steam id.

If you still want to do this, then I will add you to the repo and upload my changes so you can start.
I'll not take a look at this until morning when I'm awake though. 😴

**Comment by DunkleMango** [comment]
I've uploaded my changes. You can now view the website at
https://dunklemango.github.io/StarboundModManager/

**Comment by AbsolofDarkness** [comment]
I kinda expected to not get paid for this :P. I just put that there cause I'm actually trying to get a job. I'm just here to help... and to be honest I'm bored so I need something to work on XD. Also, thanks for liking my portfolio! It's the culmination of six months of classes, so I'm pretty proud of it. But I'm still open to helping.

**Comment by DunkleMango** [comment]
Yeah, I just did not want to disappoint you, so I asked first.
So thank you again for wanting to support the project!
Then you are going to be added to the repo now.
Also, best of luck for your job search! 😃

**Comment by DunkleMango** [comment]
You should have received the invitation link now :)
